### ISSUE TITLE
Executing commands in a container via portainerssh

### ISSUE THREAD

**Issue by ovarchenko** [devbranch-vadym/portainerssh#41]
If run `portainerssh <container> -c "ls"` the command return the result, but if run `portainerssh <container> -c "ls -l"` return an error...
`OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "ls -l": executable file not found in $PATH: unknown`
If remove the quotes, only `ls` will executed and ignored `-l`

Need to change `Command` type to []string, just like Docker does
in `type ContainerExecParams struct` [api.go](https://github.com/devbranch-vadym/portainerssh/blob/master/pkg/portainer/api.go#L27)

**Comment by devbranch-vadym** [comment]
@ovarchenko can you please check if #43 fixes this for you?
Thanks!

**Comment by ovarchenko** [comment]
Everything is fine.
Thanks for the quick response.
