### ISSUE TITLE
Return error code in portainerssh -c "..."

### ISSUE THREAD

**Issue by ovarchenko** [devbranch-vadym/portainerssh#57]
**Describe the bug**
If run portainerssh with the flag `-c` or `--command` always return `0`

**To Reproduce**
1. `portainerssh YOUR_CONTAINER -c "cat file_not_exist"`
2. `echo $?`

**Expected behavior**
Return the error code of the command that is executed in the container.

**Actual behavior**
Returns the error code of the `portainerssh`

**Environment:**
 - Portainer version `2.11.0`
 - `portainerssh` version `1.5.0`

**Comment by devbranch-vadym** [comment]
Probably could be achieved by retrieving the `ExitCode` after the connection is closed:
https://docs.docker.com/engine/api/v1.41/#operation/ExecInspect

**Comment by devbranch-vadym** [comment]
Hi @ovarchenko , can you please try #58 ? That should theoretically help.

**Comment by ovarchenko** [comment]
Hi @devbranch-vadym
Now it works as it should.
